### ISSUE TITLE
REQUEST: add changelog.md file for meaningfull release message

### ISSUE THREAD

**Issue by filippo-ferrando** [Elemento-Modular-Cloud/elemento-gui#11]
I suggest to add a changelog file that would be mapped to the release message, this will simplify the gathering of info that we need to add to the release page

**Comment by fvalle1** [comment]
@francescochiapello

**Comment by filippo-ferrando** [comment]
I tried adding a test changelog file in develop branch, i didn't added the version because i think it is redundant with the release title

**Comment by fvalle1** [comment]
no, please leave the title in the .md

**Comment by filippo-ferrando** [comment]
pr #15 solve this problem, the release message is a parse of the changelog file containing only the "Release notes" of the last version
