### ISSUE TITLE
incorrect infos for the latest release

### ISSUE THREAD

**Issue by MMogna** [Elemento-Modular-Cloud/elemento-gui#20]
As it's shown in the following images a missed update to the changelog.md file before the last build resulted into:
- having a version that is not progressing to 1.0.5 instead returning back to 1.0.3
- the release notes are for the 1.0.4 version and build and are reported again for this new build

![Screenshot 2024-10-02 at 16 05 55](https://github.com/user-attachments/assets/2da2ad4c-1681-41a7-a0c2-0f5db935c4f1)
![Screenshot 2024-10-02 at 16 08 19](https://github.com/user-attachments/assets/7c79ae04-0d5a-4889-9012-66d2189b0489)

**Comment by fvalle1** [comment]
@francescochiapello be careful about version package.json has 1.0.3

**Comment by fvalle1** [comment]
https://github.com/Elemento-Modular-Cloud/elemento-gui/commit/cc0e7703dcf0561455b79f6ba6fb709423cf9336 will restart everything
