### ISSUE TITLE
PCIIDs are still at 2 years ago listings

### ISSUE THREAD

**Issue by fvalle1** [Elemento-Modular-Cloud/elemento-gui#8]

**Comment by fvalle1** [comment]
See https://github.com/Elemento-Modular-Cloud/elemento-monorepo-app/issues/17

**Comment by fvalle1** [comment]
@gabrielefronze we should consider to make https://github.com/Elemento-Modular-Cloud/elemento-pciid-mapper public in order to let the GUI auto update

**Comment by fvalle1** [comment]
@filippo-ferrando can we run `python3 pciid-mapper.py` in the GH actions?

**Comment by fvalle1** [comment]
@francescochiapello can you, at least, verify to be updated before building?

**Comment by fvalle1** [comment]
https://github.com/Elemento-Modular-Cloud/elemento-gui/commit/bbcf2421d252deef5665dcb81ab14d6a399d28b9 temporarily solves it

**Comment by filippo-ferrando** [comment]
> @filippo-ferrando can we run `python3 pciid-mapper.py` in the GH actions?

yes

**Comment by francescochiapello** [comment]
> @francescochiapello can you, at least, verify to be updated before building?

Yes @fvalle1, that's my fault, I forgot to pull the submodules.
Now I've updated the `dist` script so before to run yarn build it runs `git pull` for each submodule.
